version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vote
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/vote
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend/src:/app
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - '3001:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend/web:/app
    command: npm run dev

volumes:
  db_data:
